spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 1500
        max-interval: 10000
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:7777}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              # lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://fit-desk.netlify.app"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
#    config:
#      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://msvc-security:9091/.well-known/jwks.json


# resilience4j:
#   circuitbreaker:
#     configs:
#       default:
#         slidingWindowSize: 50
#         minimumNumberOfCalls: 20
#         permittedNumberOfCallsInHalfOpenState: 5
#         waitDurationInOpenState: 10s
#         failureRateThreshold: 70
#         eventConsumerBufferSize: 10
#     instances:
#       billingCircuitBreaker:
#         baseConfig: default


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.gateway.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway,metrics,loggers
  # endpoint:
  #   gateway:
  #     enabled: true

  
server:
  port: 9090