spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 1500
        max-interval: 10000
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:7777}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              # lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://fit-desk.netlify.app"
                allowedMethods:
                  - GET
                  - PUT
                  - DELETE
                  - PATCH
                  - POST

#    config:
#      enabled: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri:


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      billingCircuitBreaker:
        baseConfig: default


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health , gateway , info
server:
  port: 9090