spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 1500
        max-interval: 10000
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:7777}
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://fit-desk.netlify.app"
                allowedMethods:
                  - GET
                  - PUT
                  - DELETE
                  - PATCH
                  - POST
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#    config:
#      enabled: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri:

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true




management:
  endpoints:
    web:
      exposure:
        include: health , gateway , info
  server:
    port: 9090