spring:
  application:
    name: msvc-members
  datasource:
    url: jdbc:postgresql://db-fitdesk:5432/members_db
    username: members_user
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: ${MSVC_MEMBERS_PORT:9092}


eureka:
  # instance:
  #   prefer-ip-address: true
  #   instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG