spring:
  application:
    name: msvc-chat
  # data:
  #   mongodb:
  #     uri: mongodb://admin:admin@mongo-db:27017/chats
  #     database: chats
server:
  port: ${MSVC_CHAT_PORT:9096}

# springdoc:
#   api-docs:
#     path: /v3/api-docs
#   swagger-ui:
#     path: /
#     url: /v3/api-docs
#     enabled: true
#   show-actuator: true
#   use-management-port: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
