spring:
  application:
    name: msvc-chat
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo-db:27017/chats?replicaSet=rs0&authSource=admin
      database: chats

  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: http://msvc-security:9091/.well-known/jwks.json

server:
  port: ${MSVC_CHAT_PORT:9096}



eureka:
  # instance:
  #   prefer-ip-address: true
  #   instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG