spring:
  application:
    name: msvc-billing
  datasource:
    url: jdbc:postgresql://db-fitdesk:5432/billing_db
    username: billing_user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: http://msvc-security:9091/.well-known/jwks.json
server:
  port: ${MSVC_BILLING_PORT:9093}



eureka:
  # instance:
  #   prefer-ip-address: true
  #   instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
