spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/FitDesk/server-secrets.git"
          default-label: dev
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
