spring:
  application:
    name: config-server
  cloud:
    discovery:
      enabled: false

    # config:
    #   server:
    #     native:
    #       search-locations: classpath:/config
server:
  port: ${CONFIG_SERVER_PORT:7777}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /
    url: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false